basePath: /
consumes:
- application/json
definitions:
  gitParser.UserInfo:
    properties:
      id:
        description: Id пользователя в БД
        type: integer
      repo:
        description: Наименование репозитория без указания владельца
        type: string
      repoId:
        description: Id репозитория в БД
        type: integer
      token:
        description: Access token пользователя в сервисе git
        type: string
      user:
        description: Имя пользователя в сервисе git
        type: string
    type: object
  main.severityCounts:
    properties:
      high:
        type: integer
      low:
        type: integer
      moderate:
        type: integer
    type: object
host: localhost:1323
info:
  contact:
    name: Delevoper
    url: https://github.com/RomDmitriy
  description: Этот сервис ищет lock-файлы в git-репозитории и возвращает список уязвимостей
    из базы данных osv.dev.
  title: WebScan Worker API
  version: "1.0"
paths:
  /parse:
    post:
      consumes:
      - application/json
      parameters:
      - description: Наименование сервиса
        enum:
        - github
        in: query
        name: service
        required: true
        type: string
      - description: Информация о пользователе и репозитории
        in: body
        name: user_info
        required: true
        schema:
          $ref: '#/definitions/gitParser.UserInfo'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/main.severityCounts'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Парсинг git-репозитория для получения уязвимостей в lock-файлах
produces:
- application/json
schemes:
- http
swagger: "2.0"
